### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by perveil** [librauee/WBDC#2]
你好：
 最近看到您的解决方法，些许问题如下：
    feed聚类、author聚类、user聚类是如何聚类的呀？我理解的feed 聚类我可以通过feed embedding去做聚类，那么author、user 是如何聚类的吗？
  感觉像是复赛提供的....
 望不吝赐教，竞赛小白。

**Comment by librauee** [comment]
是这样的，每个author会发布不同的feed，把他所发布的所有feed的embedding求平均值 来表征这个author，然后在根据这个表征来做author的距离，user也是同理，每个user所看过的feed的embedding求平均值来表征这个user再做聚类

**Comment by perveil** [comment]
明白了，非常感谢，祝工作顺利

**Comment by xjtu-ygq** [comment]
Thank you!
